// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/repository": {
    params: {};
  };
  "/workflows": {
    params: {};
  };
  "/editor": {
    params: {};
  };
  "/ai": {
    params: {};
  };
  "/clickwrap": {
    params: {};
  };
  "/reports": {
    params: {};
  };
  "/contracts": {
    params: {};
  };
  "/contracts/new": {
    params: {};
  };
  "/contracts/:id": {
    params: {
      "id": string;
    };
  };
  "/contracts/:id/edit": {
    params: {
      "id": string;
    };
  };
  "/analytics": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/repository" | "/workflows" | "/editor" | "/ai" | "/clickwrap" | "/reports" | "/contracts" | "/contracts/new" | "/contracts/:id" | "/contracts/:id/edit" | "/analytics" | "/settings";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/_dashboard/layout.tsx": {
    id: "routes/_dashboard/layout";
    page: "/dashboard" | "/repository" | "/workflows" | "/editor" | "/ai" | "/clickwrap" | "/reports" | "/contracts" | "/contracts/new" | "/contracts/:id" | "/contracts/:id/edit" | "/analytics" | "/settings";
  };
  "routes/_dashboard/index.tsx": {
    id: "routes/_dashboard/index";
    page: "/dashboard";
  };
  "routes/_dashboard/repository.tsx": {
    id: "routes/_dashboard/repository";
    page: "/repository";
  };
  "routes/_dashboard/workflows.tsx": {
    id: "routes/_dashboard/workflows";
    page: "/workflows";
  };
  "routes/_dashboard/editor.tsx": {
    id: "routes/_dashboard/editor";
    page: "/editor";
  };
  "routes/_dashboard/ai.tsx": {
    id: "routes/_dashboard/ai";
    page: "/ai";
  };
  "routes/_dashboard/clickwrap.tsx": {
    id: "routes/_dashboard/clickwrap";
    page: "/clickwrap";
  };
  "routes/_dashboard/reports.tsx": {
    id: "routes/_dashboard/reports";
    page: "/reports";
  };
  "routes/_dashboard/contracts/index.tsx": {
    id: "routes/_dashboard/contracts/index";
    page: "/contracts";
  };
  "routes/_dashboard/contracts/new.tsx": {
    id: "routes/_dashboard/contracts/new";
    page: "/contracts/new";
  };
  "routes/_dashboard/contracts/$id.tsx": {
    id: "routes/_dashboard/contracts/$id";
    page: "/contracts/:id";
  };
  "routes/_dashboard/contracts/$id.edit.tsx": {
    id: "routes/_dashboard/contracts/$id.edit";
    page: "/contracts/:id/edit";
  };
  "routes/_dashboard/analytics.tsx": {
    id: "routes/_dashboard/analytics";
    page: "/analytics";
  };
  "routes/_dashboard/settings.tsx": {
    id: "routes/_dashboard/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/_dashboard/layout": typeof import("./app/routes/_dashboard/layout.tsx");
  "routes/_dashboard/index": typeof import("./app/routes/_dashboard/index.tsx");
  "routes/_dashboard/repository": typeof import("./app/routes/_dashboard/repository.tsx");
  "routes/_dashboard/workflows": typeof import("./app/routes/_dashboard/workflows.tsx");
  "routes/_dashboard/editor": typeof import("./app/routes/_dashboard/editor.tsx");
  "routes/_dashboard/ai": typeof import("./app/routes/_dashboard/ai.tsx");
  "routes/_dashboard/clickwrap": typeof import("./app/routes/_dashboard/clickwrap.tsx");
  "routes/_dashboard/reports": typeof import("./app/routes/_dashboard/reports.tsx");
  "routes/_dashboard/contracts/index": typeof import("./app/routes/_dashboard/contracts/index.tsx");
  "routes/_dashboard/contracts/new": typeof import("./app/routes/_dashboard/contracts/new.tsx");
  "routes/_dashboard/contracts/$id": typeof import("./app/routes/_dashboard/contracts/$id.tsx");
  "routes/_dashboard/contracts/$id.edit": typeof import("./app/routes/_dashboard/contracts/$id.edit.tsx");
  "routes/_dashboard/analytics": typeof import("./app/routes/_dashboard/analytics.tsx");
  "routes/_dashboard/settings": typeof import("./app/routes/_dashboard/settings.tsx");
};